root = { stmt } , [ expr ] ;
stmt = expr , ";" ;
expr = binding
     | declaration ;
binding = alternative , ":=" , binary
        | alternative , ":" binary , "=" , binary ;
declaration = alternative , ":" , binary
            | binary ;
binary = index , index , application
       | application ;
application = alternative , function , { "," , function }
            | function ;
function = index , "=>" , binary | index ;
index = index , "'" , dotted
      | dotted ;
dotted = dotted , "." , alternative
       | alternative ;
alternative = "$" , atomic
            | atomic ;
atomic = "(" , [ binary , { ";" , binary } ] , ")"
       | "[" , [ binary , { ";" , binary } ] , "]"
       | "{" , root , "}"
       | ?integer?
       | ?real?
       | ?identifier?
       | ?string? ;
